### ISSUE TITLE
Slamming Sense's internal API with authentication requests

### ISSUE THREAD

**Issue by firestormo** [scottbonline/sense#21]
[https://community.sense.com/t/download-or-api-to-feed-pvoutput/3033/25](https://community.sense.com/t/download-or-api-to-feed-pvoutput/3033/25)

RyanAtSense
Community Manager

Hey guys. It’s come to the engineering team’s attention that the unofficial APIs posted are slamming our internal API with authentication requests pretty much constantly. This is causing some performance degradation on our end. We have no issue with these APIs existing and being utilized by our userbase, but they should not be coded in such a way as to negatively affect performance for our teams and the rest of our users. We’ve contacted the owners of both Github repositories so they can make the necessary changes to their code.

**Comment by kbickar** [comment]
The only authentication call is at the startup, unless they're saying that every API call that uses the access token is an authentication - if that's the case then I don't think there's anything to be done.  It'd be great if they could comment more here about it.

**Comment by firestormo** [comment]
i added you to the email thread I started with their guy on their forum..  waiting for replies from him

**Comment by kbickar** [comment]
Added a comment to the readme in the most recent commit
