### ISSUE TITLE
pip install sense_energy fails because it can't find README.md

### ISSUE THREAD

**Issue by EricPalmquist** [scottbonline/sense#22]
When I try to install using 'sudo pip install sense_energy -v -v -v'  I get the error below.  Not sure why it is complaining about README.md since that seems to exist.  Any ideas?

  Added sense_energy from https://files.pythonhosted.org/packages/31/af/93c297b301f7daffea733708528c00048ef72fa544ca1457148331662185/sense_energy-0.4.1.tar.gz#sha256=00091d9f81a70135810635951c2fbd594e3ff247786726778a218448f7569577 to build tracker '/tmp/pip-req-tracker-MO4tPB'
  Running setup.py (path:/tmp/pip-install-D2SLlB/sense-energy/setup.py) egg_info for package sense-energy
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-D2SLlB/sense-energy/setup.py", line 3, in <module>
        with open("README.md", "r") as fh:
    **IOError: [Errno 2] No such file or directory: 'README.md'**
Cleaning up...
  Removing source in /tmp/pip-install-D2SLlB/sense-energy
Removed sense_energy from https://files.pythonhosted.org/packages/31/af/93c297b301f7daffea733708528c00048ef72fa544ca1457148331662185/sense_energy-0.4.1.tar.gz#sha256=00091d9f81a70135810635951c2fbd594e3ff247786726778a218448f7569577 from build tracker '/tmp/pip-req-tracker-MO4tPB'
Removed build tracker '/tmp/pip-req-tracker-MO4tPB'
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-D2SLlB/sense-energy/

**Comment by SherlocksHat** [comment]
I also have the same issue: "IOError: [Errno 2] No such file or directory: 'README.md"

**Comment by kbickar** [comment]
What version of python/pip are you running?

**Comment by EricPalmquist** [comment]
I am using python 2.7 and pip 18.  I was able to get it installed using:

> sudo pip install -e git+https://github.com/scottbonline/sense.git#egg=sense_energy

**Comment by tavdog** [comment]
The readme still has erroneous install  instructions. pip install doesn't work for.  Can you add some manual install instructions maybe ?

**Comment by kbickar** [comment]
Update - the 2.7 version should install properly with pip now
