### ISSUE TITLE
Error appearing with new websocket version

### ISSUE THREAD

**Issue by SherlocksHat** [scottbonline/sense#24]
I upgraded to the newest version of websocket (released this month) and the sense_api now throws an error:
   ```
 from sense_api import Senseable
  File "/home/user/sense/sense_energy/sense_api.py", line 5, in <module>
    from websocket import create_connection
ImportError: cannot import name create_connection

```

**Comment by kbickar** [comment]
Make sure you have the package "websocket-client" installed.  You can do so with the command: `pip install websocket-client`  

It hasn't had a release this month so I suspect you're using a different package

**Comment by SherlocksHat** [comment]
hmm your right. I seemed to be looking at the Ubuntu variant. We can close this an I'll keep investigating the issue on my end.
