### ISSUE TITLE
'Senseable' object has no attribute 'rate_limit'

### ISSUE THREAD

**Issue by therealmysteryman** [scottbonline/sense#31]
When calling the update_realtime, I get this error 'Senseable' object has no attribute 'rate_limit' if I call the function after the inital 30 seconds.

**Comment by kbickar** [comment]
Can you post a sample of the code you're using?

**Comment by therealmysteryman** [comment]
Calling the sense.update_realtime to refresh the data, here an example that cause the issue for me. I may be misinterpreting the use of the function. 

`sense = Senseable()
    sense.authenticate(username, password)
    sense.update_realtime()
    sense.update_trend_data()
    print ("Active:",sense.active_power,"W")
    print ("Active Solar:",sense.active_solar_power,"W")
 ....
    time.sleep(31)
     **sense.update_realtime()**

then 'Senseable' object has no attribute 'rate_limit' error `

**Comment by johntdyer** [comment]
I dont understand why this was closed and how that commit addressed this issue

**Comment by kbickar** [comment]
The commit added the attribute `rate_limit` to the `Senseable` object.  Are you still seeing an issue with it?
