### ISSUE TITLE
Question: Disconnect logs?

### ISSUE THREAD

**Issue by futzlarson** [scottbonline/sense#34]
Due to my power box being in a crawlspace, the wifi signal is weak, often disconnecting. I put in a support ticket with Sense and they show me some logs:

![image](https://user-images.githubusercontent.com/1168673/78185031-78173980-7438-11ea-9812-c7cc9350e1e7.png)

When I asked if this was available in some way (as there isn't a great way to see that info in the mobile or web app), they said:

> Unfortunately, the disconnects logs are currently unavailable in the Sense app, however, that is not a suggestion we have had before so I have passed that along to our Product team as well as I think that would be a great feature addition in the future.

All of this is to say, are these logs available via the API? My main interest in using this is to more closely monitor the frequency and duration of these disconnects.

**Comment by kbickar** [comment]
Just did some experiments and the answer is: No, not really. They don't include connects/disconnects in the event list, it doesn't have any "uptime" values and it's not reliable enough just to check the data coming from it to know if it's online/offline.

**Comment by futzlarson** [comment]
Fair enough. I appreciate you looking into it!
