### ISSUE TITLE
JSONDecodeError After One Hour

### ISSUE THREAD

**Issue by afurze** [scottbonline/sense#55]
I updated my code to use the new request_token but now I'm having an issue where, one hour after I do a .authenticate() and get an access token, I start getting JSONDecodeErrors and have to generate a new session and access_token.

Traceback (most recent call last):
  File "/root/wallclock/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/wallclock/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/wallclock/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/wallclock/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/wallclock/weather.py", line 78, in get_weather
    sense.update_realtime()
  File "/root/wallclock/venv/lib/python3.8/site-packages/sense_energy/senseable.py", line 135, in update_realtime
    next(self.get_realtime_stream())
  File "/root/wallclock/venv/lib/python3.8/site-packages/sense_energy/senseable.py", line 145, in get_realtime_stream
    result = json.loads(ws.recv())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Even if I'm calling it frequently, the next attempt one hour after the access_token was generated I start getting these errors.  If I try to call the renew_auth method, I get a credential error message.

**Comment by kbickar** [comment]
Maybe you can share the code?  There are a few variables you need to keep track of after authentication.  If any of them are missing (like the device id) then it'll require you to reauthenticate and won't work with the request token either
```
    # Store auth data:
    access_token = sense.sense_access_token
    user_id = sense.sense_user_id
    monitor_id = sense.sense_monitor_id
    device_id = sense.device_id
    refresh_token = sense.refresh_token

   ...

    # Load data in new instance
    sense = Senseable()    
    sense.load_auth(access_token, user_id, device_id, refresh_token)
    sense.set_monitor_id(monitor_id)

**Comment by afurze** [comment]
Here's the relevant snippet from my code

`# Get sense data
    with open("sense_conf.json", "r") as infile:
        sense_conf = json.load(infile)

    sense = Senseable()

    sense.set_monitor_id(sense_conf['monitor_id'])
    sense.load_auth(
        access_token=sense_conf['access_token'],
        user_id=sense_conf['user_id'], 
        refresh_token=sense_conf['refresh_token'],
        device_id=sense_conf['monitor_id']
    )

    # Write new tokens
    #sense.renew_auth()
    #sense_conf["access_token"] = sense.sense_access_token
    #sense_conf["refresh_token"] = sense.refresh_token
    #with open("sense_conf.json", "w") as outfile:
    #    outfile.write(json.dumps(sense_conf))

    sense.update_realtime()
    sense.update_trend_data()`

It's a small Flask app, so the same code gets executed on each page load.  For the first hour, everything is happy, after that hour, it fails.

**Comment by kbickar** [comment]
I think `device_id=sense_conf['monitor_id']` is the problem - the device_id refers to the device making the API call, not the monitor

**Comment by afurze** [comment]
That's my mistake, I thought they were interchangeable, thank you!

**Comment by afurze** [comment]
Issue re-occurred despite this change.

**Comment by israndy** [comment]
Drat, I thought I checked the other issues for being a dupe, do we know why the API fails after an hour yet?

**Comment by kbickar** [comment]
Not really sure.  It's not happening with the async version at least and there are different libraries used between them.  I'm doing some testing, but it takes a while

**Comment by kbickar** [comment]
Ok, the auth expires every hour it seems.  Updating the trends automatically renews it if it's expired but updating the realtime doesn't.  As a workaround you can call `sense.update_trend_data()` before  `sense.update_realtime()` and it'll work fine.

I'll update the realtime to also renew the auth

**Comment by israndy** [comment]
Thx, trying it now

**Comment by kbickar** [comment]
Changes added to 0.11.1 release
