### ISSUE TITLE
Realtime device usage updates in HA

### ISSUE THREAD

**Issue by lymanepp** [scottbonline/sense#66]
Has any consideration been given to using async_realtime_stream in the HA integration (without Single=True)? Having real-time push updates would make the data more useful (to me, anyways). It wouldn't have any more impact to Sense than leaving a browser tab open to the "Now" tab. Suppressing updates for a device when the data hasn't changed would limit the amount of data stored in HA.

**Comment by kbickar** [comment]
Yes, currently there are 5 messages sent per minute to get the realtime data from the Sense API but to keep the stream open would be 65 messages per minute plus it would mean keeping a connection open with the Sense servers.  The Sense team wouldn't be happy with that

**Comment by lymanepp** [comment]
> The Sense team wouldn't be happy with that

But it wouldn't be any different than leaving a browser tab open on the "Now" tab.

**Comment by kbickar** [comment]
But most people don't leave a browser open to that tab.  If it were used in HomeAssistant it would be like thousands of people leaving open their browser when most of them probably don't even need that extra frequency of update

**Comment by lymanepp** [comment]
Thanks for the feedback.
