### ISSUE TITLE
causes Sense App to misbehave

### ISSUE THREAD

**Issue by mschwartz** [scottbonline/sense#69]
I am using the API to poll once per minute.

The Sense App on my phone and tablets repaint the Always On and Add Device screens.

It is clearly a Sense (the company/engineering team) problem, but ideally this API should just work.

To reproduce:

1) call login
2) in a loop:
2a) call update_trend_data
2b) sleep 1 minute
2c) repeat from step 2)

If you want to reproduce it quicker, set the sleep time to 5 seconds or even 2 or 1.

I am posting this here to see if you can figure out a workaround, and to alert anyone who wants to use this unofficial API about the problem.

I exchanged several emails with Sense support and urged them to provide a public API and/or fix the bug this causes.

**Comment by mschwartz** [comment]
Also, missing a call to get the Mains values (similar to getting the voltage and frequency)./

**Comment by kbickar** [comment]
What's the problem that you're seeing?

**Comment by mschwartz** [comment]
This is my custom app:

![2024-11-05 at 1 44 PM](https://github.com/user-attachments/assets/be926115-ab97-48d1-976a-2146dd4736a9)

**Comment by mschwartz** [comment]
I will upload two videos/screen recordings from my ipad exhibiting the bug.  I shared these with Sense support.


https://github.com/user-attachments/assets/f8f78b8a-85ea-40fa-85e4-0a5f931f9cb5


https://github.com/user-attachments/assets/b2ffa585-847d-4548-a9eb-878837d2567c


https://github.com/user-attachments/assets/998ebde2-7306-48d0-ab12-489eb87074d0

**Comment by mschwartz** [comment]
see how the app refreshes and jumps to the top of the lists?  Or the popover to select "Add Device" just goes away on its own.

**Comment by mschwartz** [comment]
I paused the program that polls using this API and the bugs go away entirely.

**Comment by mschwartz** [comment]
Bug happens if I poll 1/minute, 1/15seconds, etc.

The time it takes the app to bug refresh the screen is not tied to poling time.  It's usually 1-4 seconds.

**Comment by kbickar** [comment]
Well it's possible the API is confused by being accessed simultaneously by two users at once.  I'd guess the same thing would happen if you accessed it through two devices at the same time too

**Comment by mschwartz** [comment]
![2024-11-05 at 1 56 PM](https://github.com/user-attachments/assets/0f832ef8-7ae0-4c8f-ba98-b0af45c60e92)

**Comment by mschwartz** [comment]
@kbickar I am really appreciative of this repo and your efforts.

**Comment by mschwartz** [comment]
Is it possible that your code is messing with cookies, logging in too often, or something along those lines?

Has anyone else (HA users) had problems?

**Comment by kbickar** [comment]
That's pretty frequent to poll the trend data too, it only updates once an hour for most stuff anyways. 

Haven't heard any issues reported from other people

**Comment by mschwartz** [comment]
The trend data is being polled every 15 minutes, when my app tries to login again.

The current production and consumption (and frequency, etc.) data are polled ideally 1/second.  That way I can turn on a poll pump and see the values change within 1 second.

**Comment by mschwartz** [comment]
I'm not an expert Python programmer by any stretch.  I know enough to be dangerous.  This code may not be the best way to express this.

What's not shown is the self.set_state() call publishes all the keys in the object passed as MQTT messages.  MQTT messages are not sent if the key/value data are not changed.

My client app subscribes to those messages and sees updates 1/POLL_FREQ and updates the graphs and numbers on the screen (screenshot above).

```
POLL_FREQ = 60 # seconds

async def run(self):
        while True:
            try:
                print("RUN: Connecting to sense...")
                self.timeout = 60 * 15 / POLL_FREQ
                print("self.timeout = ", self.timeout)
                self.sense = Senseable()
                self.sense.authenticate(username, password)
                self.sense.rate_limit = POLL_FREQ
                self.sense.update_trend_data()
            except Exception as e:
                print('Excpeption:', e)
                continue

            while True:
                try:
                    self.timeout = self.timeout - 1
                    if self.timeout <= 0:
                        print("RUN: timeout, Reconnecting...")
                        break
                    await asyncio.sleep(POLL_FREQ)  # sleep for one second
                    self.sense.update_realtime()

                    current = {
                        "devices": self.sense.active_devices,
                        "consumption": self.sense.active_power,
                        "solar": self.sense.active_solar_power,
                        "voltage": self.sense.active_voltage,
                        "frequency": self.sense.active_frequency,
                    }
                    daily = {
                        "consumption": self.sense.daily_usage,
                        "production": self.sense.daily_production,
                        "production_pct": self.sense.daily_production_pct,
                        "net_production": self.sense.daily_net_production,
                        "from_grid": self.sense.daily_from_grid,
                        "to_grid": self.sense.daily_to_grid,
                        "solar_powered": self.sense.daily_solar_powered,
                    }
                    weekly = {
                        "consumption": self.sense.weekly_usage,
                        "production": self.sense.weekly_production,
                        "production_pct": self.sense.weekly_production_pct,
                        "net_production": self.sense.weekly_net_production,
                        "from_grid": self.sense.weekly_from_grid,
                        "to_grid": self.sense.weekly_to_grid,
                        "solar_powered": self.sense.weekly_solar_powered,
                    }
                    monthly = {
                        "consumption": self.sense.monthly_usage,
                        "production": self.sense.monthly_production,
                        "production_pct": self.sense.monthly_production_pct,
                        "net_production": self.sense.monthly_net_production,
                        "from_grid": self.sense.monthly_from_grid,
                        "to_grid": self.sense.monthly_to_grid,
                        "solar_powered": self.sense.monthly_solar_powered,
                    }
                    yearly = {
                        "consumption": self.sense.yearly_usage,
                        "production": self.sense.yearly_production,
                        "production_pct": self.sense.yearly_production_pct,
                        "net_production": self.sense.yearly_net_production,
                        "from_grid": self.sense.yearly_from_grid,
                        "to_grid": self.sense.yearly_to_grid,
                        "solar_powered": self.sense.yearly_solar_powered,
                    }

                    stats = {
                        "daily": daily,
                        "weekly": weekly,
                        "monthly": monthly,
                        "yearly": yearly,
                    }
                    new_state = {
                        "current": current,
                        "stats": stats
                    }
                    self.set_state(new_state)

#                     print(self.sense._realtime)

                    print ("\n")
                    print ("Active Devices:",", ".join(self.sense.active_devices))
                    print ("   Consumption:", self.sense.active_power, "W")
                    print ("         Solar:", self.sense.active_solar_power, "W")
                    print ("         Daily:", self.sense.daily_usage, "KWh")
                    print ("   Daily Solar:", self.sense.daily_production, "KWh")
                except Exception as e:
                    print('Excpeption:', e)
                    break
```

**Comment by kbickar** [comment]
A few things - if you're using asyncio already, then you should use ASyncSensable instead of Senseable.  The authentication works basically the same, but it'll be faster.

If you want updates that frequently, you should keep open the websocket stream and use  `async_realtime_stream` rather than `update_realtime` since `update_realtime` opens the websocket, reads the header data, reads the real data, then closes the websocket while if you keep reading from `async_realtime_stream`  (which takes an optional callback function when data is received) then you get the data messages roughly every second anyways.  It's quite a lot of bandwidth from the API so I wouldn't recommend leaving that running forever

**Comment by mschwartz** [comment]
There weren't any AsyncSensable (or any API) examples in the repo.  Or I missed them.

Are they just drop in replacements for the code I posted?

How do I keep this websocket open?  Is this automatic if I call async_realtime_stream() ?

Like I wrote, I'm not a Python expert...

**Comment by kbickar** [comment]
Basic example would be:
```
        def update_func():
            # update gui with latest realtime data or whatever
            pass
        sense = ASyncSenseable()
        await sense.authenticate(username, password)
        task = asyncio.ensure_future(sense.get_realtime_future(update_func))
        ...
        await task
```

**Comment by mschwartz** [comment]
Figured out the async on my own.

Works great.  No bug in the app anymore.

But Sense still has bugs to fix :)

Thanks!

**Comment by kbickar** [comment]
Great!  Hopefully sense can update their side at somepoint
